# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidaty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('email', models.CharField(max_length=222)),
                ('message', models.CharField(max_length=222)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Candidato',
                'ordering': ['join_date'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='candidaty',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job', verbose_name='Vaga'),
        ),
    ]
